version: "3.0"

services:
  localstack:
    image: localstack/localstack:4.6.0
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"

    environment:
      - DEBUG="1"
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=development

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

    networks:
      - development

networks:
  development:
    name: development
    driver: bridge
