<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BadgeSmith.Api\BadgeSmith.Api.csproj"/>
  </ItemGroup>

</Project>
